@ClientesService_HostAddress = http://localhost:5068


### Teste GET paginado
GET {{ClientesService_HostAddress}}/api/clientes?page=2&pageSize=5
Accept: application/json

### Teste POST
POST {{ClientesService_HostAddress}}/api/clientes
Accept: application/json
Content-Type: application/json

{
  "nome": "Cliente {{$randomInt 1000 9999}}",
  "cpf": "37008771029",
  "renda":  {{$randomInt 800 7500}},
  "nascimento": "{{$randomInt 1960 2010}}-{{$datetime "MM-dd"}}"
}

